# Build
FROM golang:1.21 AS build

WORKDIR /go/src/tb

COPY go.mod go.sum .
RUN go mod download
ENV CGO_ENABLED=0
RUN go install tailscale.com/tsnet tailscale.com/tsweb

COPY . .
RUN mkdir -p /out
RUN go build -o /out/tb ./tb

# Deploy
FROM debian:bookworm

RUN apt-get update && apt-get install -y \
    ca-certificates git curl jq strace

COPY --from=build /out/tb /tb
CMD ["/tb"]