# Build
FROM golang:1.21 AS build

WORKDIR /go/src/tbw
RUN mkdir -p /out

COPY go.mod go.sum .
RUN go mod download
ENV CGO_ENABLED=0
ENV GOBIN=/out
RUN go install github.com/bradfitz/go-tool-cache/cmd/go-cacher

COPY . .
RUN go install ./tbw

# Deploy
FROM debian:bookworm

RUN apt-get update && apt-get install -y \
    ca-certificates git curl jq strace \
    iptables nftables kmod

COPY --from=build /out/tbw /tbw
COPY --from=build /out/go-cacher /usr/local/bin/go-cacher

CMD ["/tbw"]
